int write_indexes()
{
    index_report_customs[0]=auto_reset_crossfade_speed_on_link;
    index_report_customs[1]=nbre_memoires_visualisables_en_preset;
    index_report_customs[2]=index_midi_global_thruth;
    index_report_customs[3]=refresh_midi_chasers;
    index_report_customs[4]=view_plot_calc_number_is;
    index_report_customs[5]=index_menus_lighting_plot;
    index_report_customs[6]=symbol_selected_type;
    index_report_customs[7]=shape_selected_type;
    index_report_customs[8]=legend_view;//plot
    index_report_customs[9]=ClassicalChannelView;//512 circuits mode
    index_report_customs[10]=index_config_dmx;
    index_report_customs[11]=index_config_midi;
    index_report_customs[12]=index_config_arduino;
    index_report_customs[13]=midi_page;
    index_report_customs[14]=config_color_style_is;
    index_report_customs[15]=index_link_is_on;
    index_report_customs[16]=index_decay_tracker;
    index_report_customs[17]=adapater_is_selected;
    index_report_customs[18]=index_build_patch_from_plot;
    index_report_customs[19]=index_menu_curve;
    index_report_customs[20]=index_show_first_dim;
    index_report_customs[21]=cheat_key_off;
    index_report_customs[22]=(int)scroll_faderspace;
    index_report_customs[23]=draw_preset_selected;
    index_report_customs[24]=index_banger_is_on;
    index_report_customs[25]=index_banger_selected;
    index_report_customs[26]=index_save_mode_export_or_binary;
    index_report_customs[27]=index_allow_sunlite_dmxIN;// dmx in position sunlite
    index_report_customs[28]=index_config_general;
    index_report_customs[29]=niveauGMaster;//grand master
    index_report_customs[30]=cheat_key_off_to_key_on;
    index_report_customs[31]=clocklevel_absolutemode;//midi clock add level
    index_report_customs[32]=echo_selected;
    index_report_customs[33]=index_allow_multicore;
    index_report_customs[34]=allow_artnet_in;
    index_report_customs[35]=window_focus_id;
    index_report_customs[36]=recall_windows_focus_id;
    index_report_customs[37]=index_config_network;
    index_report_customs[38]=index_setup_gfx;
    index_report_customs[39]=core_to_assign;
    index_report_customs[40]=index_midi_clock_on;
    index_report_customs[41]=midi_BPM;
    index_report_customs[42]=show_global_view_grider;
    index_report_customs[43]=enable_launchpad;
    index_report_customs[44]=relativ_encoder_midi_clock_value;
    index_report_customs[45]=config_page_is;
    index_report_customs[46]=index_midi_affectation_autoclose;
    index_report_customs[47]=index_show_chrono;
    index_report_customs[48]=nbre_track_visualisables;
    index_report_customs[49]=chaser_operator_is;
    index_report_customs[50]=chaser_selected;
    index_report_customs[51]=index_affichage_digit_time_unit;//affichage des unités après virgule
    index_report_customs[52]=launchpad_chaser_mode;
    index_report_customs[53]=index_enable_edit_chaser;
    index_report_customs[54]=chaser_midi_rows;
    index_report_customs[55]=line_list_is;
    index_report_customs[56]=waver_control;
    index_report_customs[57]=wave_channel_preset_selected;
    index_report_customs[58]=brush_selected;
    index_report_customs[59]=iCatPageis;
    index_report_customs[60]=surface_type;
    index_report_customs[61]=grid_icat_modulo;
    index_report_customs[62]=index_midi_auto_demute;
    index_report_customs[63]=index_midi_mute_on_lfo;
    index_report_customs[64]=index_text_auto_close;
    index_report_customs[65]=index_config_core;
    index_report_customs[66]=show_gridplayer_in_seq;
    index_report_customs[67]=index_auto_mute_cuelist_speed;
    index_report_customs[68]=Midi_Force_Go;
    index_report_customs[69]=BPM_WAVE_RATE;
    index_report_customs[70]=index_config_tab_hotkeys;// sab 12/08/2016 Fenêtre des config - onglet des hot keys

    return(0);
}
