int clear_plot_legend()
{

    for(int i=0; i<39; i++)
    {
        sprintf(plot_renseignements[i],"-");
    }
    sprintf(plot_renseignements[0],"TITRE DU SPECTACLE");
    sprintf(plot_renseignements[1],"COMPAGNIE");
    sprintf(plot_renseignements[19],"1 CARRE 1 METRE");
    sprintf(plot_renseignements[20],"LightPlan generated by");
    sprintf(plot_renseignements[21],"WhiteCat LightingBoard");

    return(0);
}
